### ISSUE TITLE
Forums "Corrupted Content Error"

### ISSUE THREAD

**Issue by PrinceKael** [void-linux/void-linux.github.io#14]
My apologies in advance if this isn't the preferred method of contact.

The forums, forum.voidlinux.org won't load at all. Firefox 63 is showing the following error:

`Corrupted Content Error`
`The site at https://forum.voidlinux.org/ has experienced a network protocol violation that cannot be repaired.`

`The page you are trying to view cannot be shown because an error in the data transmission was detected.`

    Please contact the website owners to inform them of this problem.

I have also archived the following site to show that it's just not me:

http://web.archive.org/web20181104173536/http://downforeveryoneorjustme.com/forum.voidlinux.org

**Comment by Vaelatern** [comment]
The forum box seems down. @void-linux/void-ops ?

**Comment by the-maldridge** [comment]
The forum is not a void managed machine.  This is not something that we have the capacity to fix.

**Comment by the-maldridge** [comment]
The forum has been gone for a fairly long time.  Closing.
