### ISSUE TITLE
show error if no results on /packages/?

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-linux.github.io#147]
At the moment, there is no clear message if a search query returns no results, which some users might see as the search not completing. Having some message that says "no results found" or similar could be good. If a welcome change, I can work on this.

**Comment by Johnnynator** [comment]
Sure, go ahead and give it a simple message on empty results.

**Comment by classabbyamp** [comment]
![image](https://user-images.githubusercontent.com/5366828/122658900-5048ea00-d140-11eb-8bf8-4c83bf3a4060.png)

How's this look?

**Comment by ericonr** [comment]
I like it! Maybe increase vertical distance from the search box a tiny bit? Not sure it'd be better, but it's the only thing that came to mind.

**Comment by classabbyamp** [comment]
![image](https://user-images.githubusercontent.com/5366828/122659105-285a8600-d142-11eb-9ae8-c7e38ef7a5d3.png)

How`s this?

**Comment by ericonr** [comment]
LGTM!
