### ISSUE TITLE
Why not add bittorrent files for downloads?

### ISSUE THREAD

**Issue by CrazyOptimist** [void-linux/void-linux.github.io#153]
Thanks for your hard work.
I find it very slow to download the latest release from the official website.
Can we add bittorrent files for them to improve download speed?

**Comment by Vaelatern** [comment]
What country are you in? You can try a local mirror.

As for torrents, we have discussed this before.

**Comment by CrazyOptimist** [comment]
Figured it out by downloading on my cloud server and uploading to my google drive.
I'm currently in North America, and ignore my personal issue, I just suggested for everyone else who might stuck in downloading.
Please close this issue if it's not needed to add bittorrent.
Thanks!

**Comment by the-maldridge** [comment]
Bittorrent is an annoying protocol to work with for the project right now, and it makes more sense for us to get better documentation out there for all the mirrors we already have.
