### ISSUE TITLE
package search results are invisible with the dark theme

### ISSUE THREAD

**Issue by paper42** [void-linux/void-linux.github.io#161]
![Screenshot from 2021-10-03 17-42-51](https://user-images.githubusercontent.com/23639164/135761407-739eb0b2-43c1-42e8-9c07-a8f3fab1d47a.png)

The dark theme is a set of overrides in `assets/css/misc.css`. Fixing this should be relatively simple, but also very useful, so this is a perfect opportunity for Hacktoberfest.

**Comment by the-maldridge** [comment]
Labelled as such.
