### ISSUE TITLE
sig file missing

### ISSUE THREAD

**Issue by bjmgeek** [void-linux/void-linux.github.io#20]
According to https://voidlinux.org/download/#verifying-file-integrity-and-its-digital-signature the signature file should be called `sha256sums.sig`, however following the instructions on that page to verify the signature fails with a 404 error:

```
$ wget http://alpha.de.repo.voidlinux.org/live/current/sha256sums.txt{,.sig}
URL transformed to HTTPS due to an HSTS policy
--2018-11-13 08:48:39--  https://alpha.de.repo.voidlinux.org/live/current/sha256sums.txt
Resolving alpha.de.repo.voidlinux.org (alpha.de.repo.voidlinux.org)... 148.251.199.112
Connecting to alpha.de.repo.voidlinux.org (alpha.de.repo.voidlinux.org)|148.251.199.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7129 (7.0K) [text/plain]
Saving to: ‘sha256sums.txt’

sha256sums.txt                   100%[==========================================================>]   6.96K  --.-KB/s    in 0s

2018-11-13 08:48:39 (234 MB/s) - ‘sha256sums.txt’ saved [7129/7129]

URL transformed to HTTPS due to an HSTS policy
--2018-11-13 08:48:39--  https://alpha.de.repo.voidlinux.org/live/current/sha256sums.txt.sig
Reusing existing connection to alpha.de.repo.voidlinux.org:443.
HTTP request sent, awaiting response... 404 Not Found
2018-11-13 08:48:39 ERROR 404: Not Found.

FINISHED --2018-11-13 08:48:39--
Total wall clock time: 0.8s
Downloaded: 1 files, 7.0K in 0s (234 MB/s)
```

**Comment by cvs-is-better** [comment]
The `void_images.asc` key is also missing from `current/`.

**Comment by the-maldridge** [comment]
Good catch, will resolve later today.

**Comment by D-Nice** [comment]
This is still missing from the latest November release. 
Also, can the mirrors be updated, if some can be no longer considered Tier 1. As an example, the EU beta repo contains additional live release dates for 20180920 and 20180921. The former was also missing a sig, the latter did have a new sig file included, but the sig does not pass. On current there, it actually has a sig file, but it's simply a copy of the one from the last release whose sig passed: 20171007

I sincerely hope people are following the verification instructions and not just blindly loading these images...

**Comment by D-Nice** [comment]
@Vaelatern it appears to be up on alpha EU mirror and passes verification on my end.

**Comment by yetanothergeek** [comment]
Not sure if I should open a new issue, but the ``sha256sums.txt.sig`` file is also missing from the http://*/live/20190217/ directory.

Also, it seems a little confusing that "current" (20181111) is older than the most recent (20190217).

**Comment by the-maldridge** [comment]
These images are not considered live or ready, which is why they have not been signed.

**Comment by yetanothergeek** [comment]
Ready or not, the images are dated and checksummed, I don't see why they couldn't be signed. But if that's the policy then maybe it should be explained somewhere. (Unless I missed it.)

**Comment by the-maldridge** [comment]
I'm happy to rm them if you'd prefer, if you try them you'll find they're broken, and documented as such in a few places.

**Comment by yetanothergeek** [comment]
If they are broken then people shouldn't have to download them to find out. I would say either remove them or add some sort of ``WARNING`` file to the directory. Even if they are only there for testing, still no reason why the testers shouldn't be able to verify their downloads.

**Comment by the-maldridge** [comment]
Its almost like they're in an unlabelled directory that you had to explore from a non-default  place to find.  I can't help people who go downloading random undocumented files from the internet and running them.

**Comment by yetanothergeek** [comment]
There is a list of mirrors on the downloads page. Select a mirror, any mirror, and follow that link. You will find a directory called "live". Inside that directory, you will find a list of dated subdirectories. Choose the most recent date. (Void is a rolling release, after all.)

I would hardly call that "downloading random files."

**Comment by Vaelatern** [comment]
You may have a point. We should provide a link for ISO downloads. Except we do, and it's not the one you followed. ![Yes, we say to get from /current.](https://i.imgur.com/QibOdQp.png)
In any event, I think this particular issue is solved. If you wish to open another issue pertaining to marking pre-release quality assets as pre-release for those who navigate by random dates, feel free to do so.

**Comment by yetanothergeek** [comment]
Yeah, not really a "random" date. According to dictionary.com the word "current" means "most recent". At any rate, your list of mirrors don't refer to a specific folder. But I agree, time to close this discussion. Thanks for your time.

**Comment by Vaelatern** [comment]
That's because they are a list. Of mirrors. Not a list of places you can get the latest live-ISOs. That list is only `/live/current/`.
They ARE the most recent. You are playing with fire when you decide that `current` not pointing to the most recent is not a sign that the latest date may be pre-release.

**Comment by yetanothergeek** [comment]
Somebody earlier said "I'm happy to rm them if you'd prefer" which kinda makes sense, if they are broken and should never be used by anyone under any circumstances.
