### ISSUE TITLE
Remove twitter from website

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-linux.github.io#208]
The twitter feed is broken, we should replace it with something else.

Sadly the Mastodon bot is broken as well.

@Gottox

**Comment by Duncaen** [comment]
Its still the official account and there is no reason to remove it.

**Comment by Anachron** [comment]
@Duncaen but ... it doesn't work? Why keep something that is broken?

**Comment by Duncaen** [comment]
Nothing stopping us from manually posting on the one of the biggest channels for announcements we have.

**Comment by Duncaen** [comment]
Oh nevermind you mean the twitter emebed.

**Comment by Anachron** [comment]
I was talking about removing the twitter feed and maybe replace it with something else that works, yes.

But since that Mastodon bot is broken, I don't think it's a good replacement.

**Comment by Gottox** [comment]
Does someone else than me have access to the mastodon account?
