### ISSUE TITLE
package search doesn't show packages from /current/

### ISSUE THREAD

**Issue by huglovefan** [void-linux/void-linux.github.io#27]
[`voidsearch.js`](https://github.com/void-linux/void-linux.github.io/blob/master/assets/js/voidsearch.js) scrapes the repositories' directory listing pages to get the list of packages, but [`/current/`](https://alpha.de.repo.voidlinux.org/current/) currently shows this text instead of a directory listing:

```
Too many files! This will crash your browser, so we're serving you this page instead.
```

this results in the packages from that directory not showing up in the [search](https://voidlinux.org/packages/)

**Comment by Chocimier** [comment]
@the-maldridge

**Comment by Vaelatern** [comment]
This is amusing. Maybe we can make it faster somehow... is there a git for javascript?

**Comment by huglovefan** [comment]
this and https://github.com/void-linux/void-linux.github.io/issues/33 were fixed in https://github.com/void-linux/void-linux.github.io/pull/35
