### ISSUE TITLE
Enable SSL on voidlinux.org

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-linux.github.io#4]
voidlinux.eu has a SSL cert, voidlinux.org does not.

**Comment by ErinVoid** [comment]
Think the problem is actually getting http to redirect to https. https://v.o works for me as does http://v.o

**Comment by ErinVoid** [comment]
This appears to be resolved now and http appears to redirect to https. Can/should it be closed down?

**Comment by Trojan295** [comment]
Confirmed from my side, voidlinux.org has a signed TLS certificate.
