### ISSUE TITLE
news item suggestion: 10k packages

### ISSUE THREAD

**Issue by auser509** [void-linux/void-linux.github.io#5]
It appears that xbps package collection just exceeded 10,000 items! I think this makes for a nice milestone to be celebrated, and potentially announced over a brief news item, as well as over the twitter channel.

**Comment by maxice8** [comment]
We are on 6575 main packages and 4059 sub-packages.

If we count them all we are in 10634, so technically yes we are over 10k packages

**Comment by the-maldridge** [comment]
eh, this feels like a cheaty way to count it.  We'll celebrate if/when we hit 10k packages that aren't subpkgs.
