### ISSUE TITLE
Void Linux Wiki Doesn't Send Confirmation Mail

### ISSUE THREAD

**Issue by PrinceKael** [void-linux/void-linux.github.io#51]
I found some issues on the Void Linux Wiki however when I make an account I'm required to confirm my email, no biggy, I applaud such feature - however the confirmation email is never sent.

My email has always been correct, I've tried waiting days and weeks and trying to send another, I've checked my spam folders - nothing.

Am I the only one having this issue or is something wrong with the email confirmation service?

**Comment by Vaelatern** [comment]
The Void wiki is, I believe, being turned down in favor of https://docs.voidlinux.org
I'd recommend you focus your efforts there.

**Comment by the-maldridge** [comment]
The wiki is practically dead at this point and has been read-only for a while.  Closing this issue.
