### ISSUE TITLE
Image signing key uses an invalid email address

### ISSUE THREAD

**Issue by theothermatt** [void-linux/void-linux.github.io#54]
The section of the downloads page at https://voidlinux.org/download/#verifying-file-integrity-and-its-digital-signature lists a signing key using the email address `images@voidlinux.eu`, which void linux [no longer owns](https://voidlinux.org/news/2019/02/voidlinux-eu-gone.html).

Presumably you have a new signing key now, but I couldn't find it anywhere?  Anyway, it would be good to see the website updated with it so people can verify their downloads.

Thanks for Void Linux, new user here enjoying it!

**Comment by the-maldridge** [comment]
Given that the entire GPG signing process is retired, I'm going to close this issue.  Our new keys use signify keys which is documented on the downloads page.
