### ISSUE TITLE
Wiki inaccesible from homepage

### ISSUE THREAD

**Issue by 123randomuser321** [void-linux/void-linux.github.io#63]
With commit 8106591a538edc123d9d266f92a4b76b8dfb31af the wiki can no longer be directly accessed from the homepage.
While you can still manually type the link into the URL-bar, this is kind of unintuitive, especially since the wiki still has a link to itself in the navigation bar.

EDIT: Removed link, I somehow broke the comment.

**Comment by Vaelatern** [comment]
The wiki is in the late stages of being phased out.

Any content you want saved should be added to https://github.com/void-linux/void-docs
