### ISSUE TITLE
live/current content is a year old

### ISSUE THREAD

**Issue by maxdevjs** [void-linux/void-linux.github.io#71]
[Downloads page](https://voidlinux.org/download/) links to [http://alpha.de.repo.voidlinux.org/live/current](https://a-hel-fi.m.voidlinux.org/live/current/) whose content is a year old.

**Comment by Hoshpak** [comment]
It's still current so nothing to worry about.

**Comment by Vaelatern** [comment]
I mean, so? We are rolling release. Those isos still update without a problem to the current packages.

**Comment by leahneukirchen** [comment]
(Install from https://github.com/leahneukirchen/hrmpf if you need a newer kernel during install.)

**Comment by anaggh** [comment]
I installed with 20191109 build. Seemed to work fine. 

+1 for monthly/weekly/daily builds if possible. Why ? Rolling release Packages get outdated too fast and the initial `xbps-install -Su` takes too long.

**Comment by aeosynth** [comment]
`current` now points to a 4 month old iso, issue resolved?
