### ISSUE TITLE
OpenPGP key is expired. Dupe of closed issue #72, however...

### ISSUE THREAD

**Issue by mozdevcontrib** [void-linux/void-linux.github.io#73]
It's likely a good idea - and a best practice - to either a) renew the key or generate a new one / b) remove it from your site. Peace.

Valid From:  8/5/17
Expires:       8/5/19
`CF24 B9C0 3809 7D8A 4495 8E2C 8DEB DA68 B482 82A4`
 Expired key still online -  A heads up!

**Comment by the-maldridge** [comment]
Not a bug.

The expired key is still used to verify the images with which it was signed.
