### ISSUE TITLE
no docs for installing apt/dpkg

### ISSUE THREAD

**Issue by Tcll** [void-linux/void-linux.github.io#78]
I've managed to get apt installed by manually creating a bunch of folders and files in `/etc/apt/` and `/var/lib/dpkg/` because `xbps-install -Su apt dpkg` doesn't create them, and apt whines it can't do anything...

so I've gotten everything configured, and can't find any way to install synaptic
my kernel is 5.4.20_1 i386
idk what ubuntu repository I need to PPA to so I can install synaptic
___

why do I need this?
because the devs of a particular app I use only put out a 64bit appimage, but may have put out a 32bit deb.

if synaptic can find it, I'll be in luck.

why synaptic?
because it's much less stressful than a terminal :)
and also better than ubuntu-software-center
(gnome-software isn't worth mentioning)

if you've ever used octoxbps, it's kinda like that, but faster, more functional, and actually installs stuff.

**Comment by Duncaen** [comment]
This is really bad, you shouldn't use two different system package managers for the same root.
You can use apk/dpkg/debootstrap to install to different root directories, but installing dpkg packages to a void root is definitively not supported and shouldn't be documented.

Also wrong repository, this should go to void-docs if it was a valid issue.

**Comment by Tcll** [comment]
> Also wrong repository, this should go to void-docs if it was a valid issue.

oh alright, sorry about that


and yeah, I really don't want to use apt anyways...
if you read the last message in that issue, I said I said I felt disgusting for even installing it...

welp, guess I can't use the app then because some higher ups made a stupid decision
ah well, guess that just means I'm more secure since electron was a dumb idea anyways (just like ActiveX) :)
I guess I got my wish XD
