### ISSUE TITLE
502 and other server issues on forum

### ISSUE THREAD

**Issue by ErinVoid** [void-linux/void-linux.github.io#8]
@gregf Appear to be getting issues when posting. Wondering if it is a workload issue. Have received a 502 error but the post is posted anyhow. Also "Server unavailable" but hitting reply posts immediately the second time. Issue has been mentioned by others, as well as it appearing to run slowly at times, in the forum but fundamentally it is working well on new host/domain.

**Comment by gregf** [comment]
I'm doubling the CPU and Ram size of the droplet. Let me know if this helps. It will be down for 5-10 minutes starting now.

**Comment by ErinVoid** [comment]
Seems okay so far and no further comments on the forum about site performance. Suggest we leave this open for a day or two and then close if no reoccurrence.
