### ISSUE TITLE
Download page is not very explicit

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-linux.github.io#88]
The Downloads page, while navigable, has several issues in its presentation. I can make PRs for at least some of these changes, but I would like to document the issues here and also have some discussion about possible changes.

* The link for where we can actually download live images and rootfs tarballs is located inside the `Download installable base live images (x86)` section, even though it contains the images for all versions of Void. It should probably be moved up in the page.
* The requirements listed are very different from what can be found in the Docs. We could put a link to the Docs page that shows the system requirements, in order to centralize this information.
* The naming convention should be documented and explained (for x86 and for ARM):
  * ROOTFS images
  * PLATFORMFS images (board specific)
  * rootfs images for systems that have their own PLATFORMFS images, but aren't marked as ROOTFS (they can still be differentiated by their extension)
  * Live systems
  * Different libc - this isn't mentioned at all in the download page
* The rootfs instructions for all ARM images are still contained in the wiki. Furthermore, https://github.com/void-linux/void-docs/issues/85 indicates that there is a wish to centralize these guides, so after the docs are ready, they can be linked instead of the wiki.
* Not all files in http://alpha.de.repo.voidlinux.org/live/current are documented:
  * GCP: I guess it's for using as servers inside Google Cloud?
  * ARM images that are not specific to some platform
  * RaspberryPi 3 image (as mentioned in #42)
  * Small addendum, Raspberry Pi image also runs on Rasp Zero.
* Possibly mention the option of using xbps-install for a chroot install without requiring the rootfs image. 

I will try to create drafts for at least some of these changes.

**Comment by flexibeast** [comment]
> We could put a link to the Docs page that shows the system requirements, in order to centralize this information.

i like this idea; it's another way of bringing attention to the existence of the Handbook, and encouraging people to consult the Handbook for authorititive information. :-)

**Comment by anaggh** [comment]
Also, the below content could be moved to https://docs.voidlinux.org and removed from here. Docs should be the single source of truth :D
```
/faq
/usage/runit
/usage/xbps
/download > Mirrors (Add link to https://docs.voidlinux.org/xbps/repositories/mirrors/index.html instead)
```
